/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class DeviceConstant {
  // 设备信息IMEI
  public static readonly DEVICE_INFO_IMEI: string = 'IMEI';
  // 设备信息IMEI1
  public static readonly DEVICE_INFO_IMEI1: string = 'IMEI1';
  // 设备信息IMEI2
  public static readonly DEVICE_INFO_IMEI2: string = 'IMEI2';
  // 设备序列号SN
  public static readonly DEVICE_INFO_SN: string = 'SN';
}