/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export default class DialerConstant {
  // 拨号盘输入的号码
  public static readonly DIALER_TEL_NUMBER_NO_SPACE: string = 'tele_number';
  // 拨号盘用于展示的号码，格式化之后的
  public static readonly DIALER_TEL_NUMBER_WITH_SPACE: string = 'tele_number_with_space';
}