/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class AppStorageConstant {
  // 回到联系人列表，如果有值，跳转到对应联系人
  public static NEW_CONTACT_ID = 'newContactId'

  // 卡片联系人信息
  public static CARD_CONTACT_INFO = 'CARD_CONTACT_INFO';

  // 名片id
  public static MYCARD_CONTACT_ID = 'MYCARD_CONTACT_ID';

  // 编辑页拍照标记
  public static EDIT_TAKE_PHOTO = 'EDIT_TAKE_PHOTO';
}