/**
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export namespace SetConstants {

  export const LEVEL_ZERO = 0;
  export const LEVEL_ONE = 1;
  export const LEVEL_TWO = 2;
  export const LEVEL_THREE = 3;
  export const LEVEL_FOUR = 4;

  export const TOTAL_TEN = 10;
  export const TOTAL_ONE_HUNDRED = 100;
  export const TOTAL_FIVE_HUNDRED = 500;
  export const TOTAL_ONE_THOUSAND = 1000;

  export const PERCENT_TEN = 10;
  export const PERCENT_EIGHT = 8;
  export const PERCENT_SIX = 6;
  export const PERCENT_FIVE = 5;
  export const PERCENT_TWO = 2;
  export const PERCENT_ONE_HUNDRED = 100;
  export const PERCENT_FIFTY = 50;
  export const PERCENT_THIRTY = 30;
  export const PERCENT_TWENTY = 20;

}